#!/bin/sh  

AimTux='./load'
Check4Update='./update'
CSGO='steam steam://rungameid/730'

echo "xcibe95x - CS:GO Hacked Launcher"  

echo "Be sure You are into Steam and the Game is Up to date."
sleep 1
echo "Launching Counter Strike Global Offensive" & $CSGO
sleep 2
cd ~/AimTux

sleep 5
echo "Checking if AimTux is Up-to-date for you."
$Check4Update

sleep 25
echo "Injecting AimTux." 
echo cibe | sudo -S $AimTux

